// Scenario catalog for the native Rust image smoke harness.
// Keeping the large data table separate from stream/render validation logic
// makes the smoke harness easier to scan when adding new coverage slices.

use super::*;

/// Returns deterministic scenario definitions for Rust image smoke.
pub(super) fn scenarios() -> Vec<Scenario> {
    vec![
        Scenario {
            name: "boot-frame",
            file_name: "boot-frame.png",
            group: ScenarioFilter::Boot,
            seed: 246,
            preset: DEFAULT_TERRAIN_PRESET,
            center_x: 0.0,
            center_z: 0.0,
            camera_offset: Vec3::new(48.0, 36.0, 62.0),
            target_height_offset: 4.0,
            coverage: None,
            shadow_debug: true,
            stream_mode: ScenarioStreamMode::Lod0,
            max_stream_ticks: 64,
            movement: None,
        },
        Scenario {
            name: "preset-seed",
            file_name: "preset-seed.png",
            group: ScenarioFilter::Presets,
            seed: 246,
            preset: 0,
            center_x: 0.0,
            center_z: 0.0,
            camera_offset: Vec3::new(44.0, 34.0, 58.0),
            target_height_offset: 4.0,
            coverage: None,
            shadow_debug: false,
            stream_mode: ScenarioStreamMode::Lod0,
            max_stream_ticks: 64,
            movement: None,
        },
        Scenario {
            name: "preset-rollingHills",
            file_name: "preset-rollingHills.png",
            group: ScenarioFilter::Presets,
            seed: 246,
            preset: 1,
            center_x: 64.0,
            center_z: -64.0,
            camera_offset: Vec3::new(48.0, 34.0, 58.0),
            target_height_offset: 5.0,
            coverage: None,
            shadow_debug: false,
            stream_mode: ScenarioStreamMode::Lod0,
            max_stream_ticks: 64,
            movement: None,
        },
        Scenario {
            name: "preset-mountainValley",
            file_name: "preset-mountainValley.png",
            group: ScenarioFilter::Presets,
            seed: 246,
            preset: 2,
            center_x: 96.0,
            center_z: -32.0,
            camera_offset: Vec3::new(60.0, 52.0, 78.0),
            target_height_offset: 7.0,
            coverage: None,
            shadow_debug: false,
            stream_mode: ScenarioStreamMode::Lod0,
            max_stream_ticks: 64,
            movement: None,
        },
        Scenario {
            name: "preset-rockyHighland",
            file_name: "preset-rockyHighland.png",
            group: ScenarioFilter::Presets,
            seed: 246,
            preset: 3,
            center_x: -64.0,
            center_z: 64.0,
            camera_offset: Vec3::new(58.0, 44.0, 62.0),
            target_height_offset: 6.0,
            coverage: None,
            shadow_debug: false,
            stream_mode: ScenarioStreamMode::Lod0,
            max_stream_ticks: 64,
            movement: None,
        },
        Scenario {
            name: "variant-low-rolling",
            file_name: "variant-low-rolling.png",
            group: ScenarioFilter::Variants,
            seed: 246,
            preset: 1,
            center_x: 0.0,
            center_z: 0.0,
            camera_offset: Vec3::new(42.0, 26.0, 54.0),
            target_height_offset: 4.0,
            coverage: None,
            shadow_debug: false,
            stream_mode: ScenarioStreamMode::Lod0,
            max_stream_ticks: 96,
            movement: None,
        },
        Scenario {
            name: "variant-ridge-heavy",
            file_name: "variant-ridge-heavy.png",
            group: ScenarioFilter::Variants,
            seed: 246,
            preset: 2,
            center_x: 96.0,
            center_z: -64.0,
            camera_offset: Vec3::new(72.0, 56.0, 86.0),
            target_height_offset: 8.0,
            coverage: None,
            shadow_debug: false,
            stream_mode: ScenarioStreamMode::Lod0,
            max_stream_ticks: 96,
            movement: None,
        },
        Scenario {
            name: "x-seam-grazing",
            file_name: "x-seam-grazing.png",
            group: ScenarioFilter::Seams,
            seed: 246,
            preset: 3,
            center_x: 32.0,
            center_z: 0.0,
            camera_offset: Vec3::new(-24.0, 2.3, -18.0),
            target_height_offset: 1.1,
            coverage: Some(ScenarioCoverage::Axis {
                axis: ChunkAxis::X,
                low: 0,
                high: 1,
            }),
            shadow_debug: false,
            stream_mode: ScenarioStreamMode::Lod0,
            max_stream_ticks: 64,
            movement: None,
        },
        Scenario {
            name: "z-seam-grazing",
            file_name: "z-seam-grazing.png",
            group: ScenarioFilter::Seams,
            seed: 246,
            preset: 3,
            center_x: 0.0,
            center_z: 32.0,
            camera_offset: Vec3::new(-18.0, 2.3, -24.0),
            target_height_offset: 1.1,
            coverage: Some(ScenarioCoverage::Axis {
                axis: ChunkAxis::Z,
                low: 0,
                high: 1,
            }),
            shadow_debug: false,
            stream_mode: ScenarioStreamMode::Lod0,
            max_stream_ticks: 64,
            movement: None,
        },
        Scenario {
            name: "chunk-corner-oblique",
            file_name: "chunk-corner-oblique.png",
            group: ScenarioFilter::Seams,
            seed: 246,
            preset: 3,
            center_x: 32.0,
            center_z: 32.0,
            camera_offset: Vec3::new(-22.0, 2.0, -24.0),
            target_height_offset: 1.4,
            coverage: Some(ScenarioCoverage::Corner {
                x_low: 0,
                x_high: 1,
                z_low: 0,
                z_high: 1,
            }),
            shadow_debug: false,
            stream_mode: ScenarioStreamMode::Lod0,
            max_stream_ticks: 64,
            movement: None,
        },
        Scenario {
            name: "far-view-multi-lod",
            file_name: "far-view-multi-lod.png",
            group: ScenarioFilter::Lods,
            seed: 246,
            preset: 2,
            center_x: 0.0,
            center_z: 0.0,
            camera_offset: Vec3::new(220.0, 118.0, 260.0),
            target_height_offset: 18.0,
            coverage: None,
            shadow_debug: false,
            stream_mode: ScenarioStreamMode::MultiLod,
            max_stream_ticks: 1600,
            movement: None,
        },
        Scenario {
            name: "lod-boundary-oblique",
            file_name: "lod-boundary-oblique.png",
            group: ScenarioFilter::Lods,
            seed: 246,
            preset: 3,
            center_x: 64.0,
            center_z: 64.0,
            camera_offset: Vec3::new(150.0, 62.0, 34.0),
            target_height_offset: 8.0,
            coverage: None,
            shadow_debug: false,
            stream_mode: ScenarioStreamMode::MultiLod,
            max_stream_ticks: 1600,
            movement: None,
        },
        Scenario {
            name: "running-stream-delta",
            file_name: "running-stream-delta.png",
            group: ScenarioFilter::Lods,
            seed: 246,
            preset: 2,
            center_x: 0.0,
            center_z: 0.0,
            camera_offset: Vec3::new(150.0, 72.0, 170.0),
            target_height_offset: 10.0,
            coverage: None,
            shadow_debug: false,
            stream_mode: ScenarioStreamMode::MultiLod,
            max_stream_ticks: 2000,
            movement: Some(ScenarioMovement {
                step_count: 48,
                step_x: 4.0,
                step_z: 1.75,
                ticks_per_step: 2,
            }),
        },
    ]
}
