// Builds deterministic TypeScript shader artifacts from checked-in WGSL sources.

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const checkOnly = process.argv.includes("--check");

const shaders = [
  {
    id: "uber",
    language: "wgsl",
    sourcePath: "src/engine/render/shaders/uber.wgsl",
    outputPath: "src/generated/render/uberShader.ts",
    sourceExport: "UBER_SHADER_SOURCE",
    metadataExport: "UBER_SHADER_METADATA",
    vertexEntryPoint: "vertexMain",
    modelVertexEntryPoint: "modelVertexMain",
    shadowVertexEntryPoint: "shadowVertexMain",
    shadowModelVertexEntryPoint: "shadowModelVertexMain",
    fragmentEntryPoint: "fragmentMain",
    skyVertexEntryPoint: "skyVertexMain",
    skyFragmentEntryPoint: "skyFragmentMain"
  },
  {
    id: "post",
    language: "wgsl",
    sourcePath: "src/engine/render/shaders/post.wgsl",
    outputPath: "src/generated/render/postShader.ts",
    sourceExport: "POST_SHADER_SOURCE",
    metadataExport: "POST_SHADER_METADATA",
    vertexEntryPoint: "postVertexMain",
    fragmentEntryPoint: "postFragmentMain"
  }
];

let hasMismatch = false;

for (const shader of shaders) {
  const source = readNormalized(shader.sourcePath);
  const generated = buildTypeScriptModule(shader, source);
  const outputAbsolutePath = resolve(root, shader.outputPath);
  const current = existsSync(outputAbsolutePath)
    ? readFileSync(outputAbsolutePath, "utf8")
    : undefined;

  if (current === generated) {
    continue;
  }

  if (checkOnly) {
    console.error(`Shader output is stale: ${shader.outputPath}`);
    hasMismatch = true;
    continue;
  }

  mkdirSync(dirname(outputAbsolutePath), { recursive: true });
  writeFileSync(outputAbsolutePath, generated);
  console.log(`Generated ${shader.outputPath}`);
}

if (hasMismatch) {
  process.exitCode = 1;
}

function readNormalized(relativePath) {
  return readFileSync(resolve(root, relativePath), "utf8")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n");
}

function buildTypeScriptModule(shader, source) {
  const sourceHash = createHash("sha256").update(source, "utf8").digest("hex");
  const metadata = {
    id: shader.id,
    sourcePath: shader.sourcePath,
    language: shader.language,
    sourceHash: `sha256-${sourceHash}`,
    ...entryPointMetadata(shader)
  };

  return [
    "/* Generated by tools/build-shaders.mjs. Do not edit by hand. */",
    "",
    "export type ShaderLanguage = \"wgsl\";",
    "",
    "export type ShaderMetadata = {",
    "  readonly id: string;",
    "  readonly sourcePath: string;",
    "  readonly language: ShaderLanguage;",
    "  readonly sourceHash: string;",
    "  readonly vertexEntryPoint: string;",
    "  readonly modelVertexEntryPoint?: string;",
    "  readonly shadowVertexEntryPoint?: string;",
    "  readonly shadowModelVertexEntryPoint?: string;",
    "  readonly fragmentEntryPoint: string;",
    "  readonly skyVertexEntryPoint?: string;",
    "  readonly skyFragmentEntryPoint?: string;",
    "};",
    "",
    `export const ${shader.metadataExport}: ShaderMetadata = Object.freeze(${JSON.stringify(metadata, null, 2)});`,
    "",
    `export const ${shader.sourceExport} = ${JSON.stringify(source)};`,
    ""
  ].join("\n");
}

function entryPointMetadata(shader) {
  const metadata = {};
  for (const key of [
    "vertexEntryPoint",
    "modelVertexEntryPoint",
    "shadowVertexEntryPoint",
    "shadowModelVertexEntryPoint",
    "fragmentEntryPoint",
    "skyVertexEntryPoint",
    "skyFragmentEntryPoint"
  ]) {
    if (shader[key] !== undefined) {
      metadata[key] = shader[key];
    }
  }

  return metadata;
}
