# Narrow adaptations for sampled depth/comparison samplers and individual array render attachments.
# Generated copies preserve the pinned submodule and fail closed if source anchors change.
foreach(ofg_file wgpu-shader-object-layout wgpu-texture)
    set(ofg_source "${CMAKE_CURRENT_SOURCE_DIR}/slang-rhi/src/wgpu/${ofg_file}.cpp")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ofg_source}")
    file(READ "${ofg_source}" ofg_text)
    if(ofg_file STREQUAL "wgpu-shader-object-layout")
        set(ofg_anchor "entry.sampler.type = WGPUSamplerBindingType_Filtering;")
        string(FIND "${ofg_text}" "${ofg_anchor}" ofg_index)
        if(ofg_index EQUAL -1)
            message(FATAL_ERROR "Pinned RHI comparison sampler anchor changed")
        endif()
        string(REPLACE "${ofg_anchor}" "entry.sampler.type = leafType->getName() && strcmp(leafType->getName(), \"SamplerComparisonState\") == 0 ? WGPUSamplerBindingType_Comparison : WGPUSamplerBindingType_Filtering;" ofg_text "${ofg_text}")
        set(ofg_anchor "entry.texture.sampleType = getSampleType(leafType->getResourceResultType());")
        string(FIND "${ofg_text}" "${ofg_anchor}" ofg_index)
        if(ofg_index EQUAL -1)
            message(FATAL_ERROR "Pinned RHI depth texture anchor changed")
        endif()
        string(REPLACE "${ofg_anchor}" "entry.texture.sampleType = (leafType->getResourceShape() & SLANG_TEXTURE_SHADOW_FLAG) ? WGPUTextureSampleType_Depth : getSampleType(leafType->getResourceResultType());" ofg_text "${ofg_text}")
        string(REPLACE "getViewDimension(leafType->getResourceShape())" "getViewDimension(SlangResourceShape(leafType->getResourceShape() & ~SLANG_TEXTURE_SHADOW_FLAG))" ofg_text "${ofg_text}")
    else()
        set(ofg_anchor "viewDesc.dimension = translateTextureViewDimension(textureImpl->m_desc.type);")
        string(FIND "${ofg_text}" "${ofg_anchor}" ofg_index)
        if(ofg_index EQUAL -1)
            message(FATAL_ERROR "Pinned RHI lighting slice-view anchor changed")
        endif()
        string(REPLACE "${ofg_anchor}" "${ofg_anchor}\n    if (desc.label && strcmp(desc.label, \"ofg-lighting-attachment\") == 0) viewDesc.dimension = WGPUTextureViewDimension_2D;" ofg_text "${ofg_text}")
    endif()
    set(ofg_generated "${CMAKE_CURRENT_BINARY_DIR}/ofg-${ofg_file}.cpp")
    file(CONFIGURE OUTPUT "${ofg_generated}" CONTENT "${ofg_text}" @ONLY)
    get_target_property(ofg_sources slang-rhi SOURCES)
    list(REMOVE_ITEM ofg_sources "src/wgpu/${ofg_file}.cpp")
    set_property(TARGET slang-rhi PROPERTY SOURCES "${ofg_sources}")
    target_sources(slang-rhi PRIVATE "${ofg_generated}")
endforeach()
